version: "3"
services:
  traefik:
    container_name: traefik
    command: 
      - --providers.docker
      - --api.insecure
      # 下面未注释的 3 行是新增的内容
      # 启用文件服务提供者，并设置配置文件的目录为 "/etc/traefik/config"
      - --providers.file.directory=/etc/traefik/config
      # 声明一个名为 web 的 entrypoint，地址为任意地址的 80 端口
      - --entryPoints.web.address=:80
      # 声明一个名为 websecure 的 entrypoint，地址为任意地址的 443 端口
      - --entrypoints.websecure.address=:443
    extra_hosts:
      "host.docker.internal": "172.18.0.1"
    image: traefik:v3.0
    ports:
      - 80:80
      # 下面 1 行是新增的内容
      - 443:443
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # 下面 2 行是新增的内容
      - /root/config:/etc/traefik/config
      - /root/certs:/etc/traefik/certs
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
