version: "3.8"

networks:
  proxy:
    external: true

volumes:
  acme:

services:
  traefik:
    image: traefik:v2.5.4
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/acme
    env_file:
      - ./.alidns.env
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.network=proxy
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entrypoint.permanent=true
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entryPoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.http.tls=true
      - --entryPoints.websecure.http.tls.certresolver=ali
      - --entryPoints.websecure.http.tls.domains[0].main=elysia.li
      - --entryPoints.websecure.http.tls.domains[0].sans=*.elysia.li
      - --certificatesresolvers.ali.acme.dnschallenge.provider=alidns
      - --certificatesresolvers.ali.acme.email=1767394@163.com
      - --certificatesresolvers.ali.acme.storage=/etc/acme/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web, websecure"
      - "traefik.http.routers.traefik.rule=Host('proxy.elysia.li')"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
